// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class AppUser
{
    public Guid UserId { get; set; }

    public string Username { get; set; } = null!;

    public string PasswordHash { get; set; } = null!;

    public string FullName { get; set; } = null!;

    public string? Phone { get; set; }

    public string? Email { get; set; }

    public string RoleCode { get; set; } = null!;

    public Guid? StoreId { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public DateTime? PasswordChangedAt { get; set; }

    public bool MustChangePassword { get; set; }

    public int FailedLoginAttempts { get; set; }

    public DateTime? LockedUntil { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<BadDebtCase> BadDebtCaseClosedByNavigations { get; set; } = new List<BadDebtCase>();

    public virtual ICollection<BadDebtCase> BadDebtCaseTransferredByNavigations { get; set; } = new List<BadDebtCase>();

    public virtual ICollection<CashVoucher> CashVoucherApprovedByNavigations { get; set; } = new List<CashVoucher>();

    public virtual ICollection<CashVoucher> CashVoucherCreatedByNavigations { get; set; } = new List<CashVoucher>();

    public virtual ICollection<Collaborator> Collaborators { get; set; } = new List<Collaborator>();

    public virtual ICollection<CustomRole> CustomRoleCreatedByNavigations { get; set; } = new List<CustomRole>();

    public virtual ICollection<CustomRolePermission> CustomRolePermissions { get; set; } = new List<CustomRolePermission>();

    public virtual ICollection<CustomRole> CustomRoleUpdatedByNavigations { get; set; } = new List<CustomRole>();

    public virtual ICollection<Customer> CustomerAssignedToUsers { get; set; } = new List<Customer>();

    public virtual ICollection<Customer> CustomerCreatedByNavigations { get; set; } = new List<Customer>();

    public virtual ICollection<CustomerDocument> CustomerDocuments { get; set; } = new List<CustomerDocument>();

    public virtual ICollection<CustomerSource> CustomerSources { get; set; } = new List<CustomerSource>();

    public virtual ICollection<CustomerVisit> CustomerVisits { get; set; } = new List<CustomerVisit>();

    public virtual ICollection<DataAccessLog> DataAccessLogs { get; set; } = new List<DataAccessLog>();

    public virtual ICollection<LoanCharge> LoanCharges { get; set; } = new List<LoanCharge>();

    public virtual ICollection<LoanCollateral> LoanCollaterals { get; set; } = new List<LoanCollateral>();

    public virtual ICollection<LoanContract> LoanContractApprovedByNavigations { get; set; } = new List<LoanContract>();

    public virtual ICollection<LoanContract> LoanContractAssignedToUsers { get; set; } = new List<LoanContract>();

    public virtual ICollection<LoanContractAttachment> LoanContractAttachments { get; set; } = new List<LoanContractAttachment>();

    public virtual ICollection<LoanContract> LoanContractCancelledByNavigations { get; set; } = new List<LoanContract>();

    public virtual ICollection<LoanContract> LoanContractCreatedByNavigations { get; set; } = new List<LoanContract>();

    public virtual ICollection<LoanContract> LoanContractDisbursedByNavigations { get; set; } = new List<LoanContract>();

    public virtual ICollection<LoanContractDocument> LoanContractDocuments { get; set; } = new List<LoanContractDocument>();

    public virtual ICollection<LoanSettlement> LoanSettlementCreatedByNavigations { get; set; } = new List<LoanSettlement>();

    public virtual ICollection<LoanSettlement> LoanSettlementFinalizedByNavigations { get; set; } = new List<LoanSettlement>();

    public virtual ICollection<LoanStatusHistory> LoanStatusHistories { get; set; } = new List<LoanStatusHistory>();

    public virtual ICollection<PolicySetting> PolicySettings { get; set; } = new List<PolicySetting>();

    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();

    public virtual Store? Store { get; set; }

    public virtual ICollection<StoreDayLock> StoreDayLocks { get; set; } = new List<StoreDayLock>();

    public virtual ICollection<UserCustomRole> UserCustomRoleCreatedByNavigations { get; set; } = new List<UserCustomRole>();

    public virtual ICollection<UserCustomRole> UserCustomRoleUsers { get; set; } = new List<UserCustomRole>();

    public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; } = new List<UserLoginHistory>();

    public virtual ICollection<UserPermission> UserPermissionCreatedByNavigations { get; set; } = new List<UserPermission>();

    public virtual ICollection<UserPermission> UserPermissionUsers { get; set; } = new List<UserPermission>();

    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();

    public virtual ICollection<UserStoreAssignment> UserStoreAssignments { get; set; } = new List<UserStoreAssignment>();
}