// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class AuditLog
{
    public Guid AuditLogId { get; set; }

    public Guid? StoreId { get; set; }

    public Guid? LoanContractId { get; set; }

    public Guid? CustomerId { get; set; }

    public string TableName { get; set; } = null!;

    public Guid RecordId { get; set; }

    public string ActionCode { get; set; } = null!;

    public string? OldData { get; set; }

    public string? NewData { get; set; }

    public Guid? ChangedBy { get; set; }

    public DateTime ChangedAt { get; set; }

    public string? Note { get; set; }

    public virtual AppUser? ChangedByNavigation { get; set; }

    public virtual Customer? Customer { get; set; }

    public virtual LoanContract? LoanContract { get; set; }

    public virtual Store? Store { get; set; }
}