// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class BadDebtCase
{
    public Guid BadDebtCaseId { get; set; }

    public Guid LoanContractId { get; set; }

    public Guid StoreId { get; set; }

    public DateTime TransferredAt { get; set; }

    public Guid? TransferredBy { get; set; }

    public decimal OutstandingPrincipalAmount { get; set; }

    public decimal OutstandingInterestAmount { get; set; }

    public decimal OutstandingPeriodicFeeAmount { get; set; }

    public decimal OutstandingLatePenaltyAmount { get; set; }

    public decimal OtherOutstandingAmount { get; set; }

    public decimal TotalOutstandingAmount { get; set; }

    public decimal RecoveredAmountTotal { get; set; }

    public string StatusCode { get; set; } = null!;

    public DateTime? ClosedAt { get; set; }

    public Guid? ClosedBy { get; set; }

    public string? Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual AppUser? ClosedByNavigation { get; set; }

    public virtual LoanContract LoanContract { get; set; } = null!;

    public virtual Store Store { get; set; } = null!;

    public virtual AppUser? TransferredByNavigation { get; set; }
}