// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class CashVoucher
{
    public Guid VoucherId { get; set; }

    public string VoucherNo { get; set; } = null!;

    public Guid StoreId { get; set; }

    public string VoucherType { get; set; } = null!;

    public string ReasonCode { get; set; } = null!;

    public DateOnly BusinessDate { get; set; }

    public DateTime VoucherDatetime { get; set; }

    public Guid? CustomerId { get; set; }

    public Guid? LoanContractId { get; set; }

    public Guid? RelatedVoucherId { get; set; }

    public string? PayerReceiverName { get; set; }

    public string? PayerReceiverAddress { get; set; }

    public string? DocumentNo { get; set; }

    public decimal Amount { get; set; }

    public string Description { get; set; } = null!;

    public bool IsAdjustment { get; set; }

    public int PrintedCount { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string PaymentMethod { get; set; } = "CASH";

    public string? BankName { get; set; }

    public string? BankAccountNumber { get; set; }

    public virtual AppUser? ApprovedByNavigation { get; set; }

    public virtual ICollection<CashVoucherAllocation> CashVoucherAllocations { get; set; } = new List<CashVoucherAllocation>();

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual Customer? Customer { get; set; }

    public virtual ICollection<CashVoucher> InverseRelatedVoucher { get; set; } = new List<CashVoucher>();

    public virtual LoanContract? LoanContract { get; set; }

    public virtual CashVoucher? RelatedVoucher { get; set; }

    public virtual Store Store { get; set; } = null!;
}