// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class CashVoucherAllocation
{
    public Guid AllocationId { get; set; }

    public Guid VoucherId { get; set; }

    public Guid? LoanContractId { get; set; }

    public Guid? ScheduleId { get; set; }

    public Guid? ChargeId { get; set; }

    public Guid? SettlementId { get; set; }

    public string ComponentCode { get; set; } = null!;

    public decimal Amount { get; set; }

    public string? Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual LoanCharge? Charge { get; set; }

    public virtual LoanContract? LoanContract { get; set; }

    public virtual LoanRepaymentSchedule? Schedule { get; set; }

    public virtual LoanSettlement? Settlement { get; set; }

    public virtual CashVoucher Voucher { get; set; } = null!;
}