// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class Collaborator
{
    public Guid CollaboratorId { get; set; }

    public string FullName { get; set; } = null!;

    public string? Phone { get; set; }

    public string? IdNumber { get; set; }

    public Guid? StoreId { get; set; }

    public string? Note { get; set; }

    public bool IsActive { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    /// <summary>
    /// Tỷ lệ hoa hồng (%) áp dụng cho CTV, ví dụ 2.50 = 2.5%. NULL = chưa cấu hình.
    /// </summary>
    public decimal? CommissionRate { get; set; }

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual Store? Store { get; set; }
}