// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CrediFlow.DataContext.Models;

public partial class CrediflowContext : DbContext
{
    public CrediflowContext(DbContextOptions<CrediflowContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppUser> AppUsers { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<BadDebtCase> BadDebtCases { get; set; }

    public virtual DbSet<CashVoucher> CashVouchers { get; set; }

    public virtual DbSet<CashVoucherAllocation> CashVoucherAllocations { get; set; }

    public virtual DbSet<Collaborator> Collaborators { get; set; }

    public virtual DbSet<CustomRole> CustomRoles { get; set; }

    public virtual DbSet<CustomRolePermission> CustomRolePermissions { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerDocument> CustomerDocuments { get; set; }

    public virtual DbSet<CustomerSource> CustomerSources { get; set; }

    public virtual DbSet<CustomerVisit> CustomerVisits { get; set; }

    public virtual DbSet<DataAccessLog> DataAccessLogs { get; set; }

    public virtual DbSet<InsuranceContract> InsuranceContracts { get; set; }

    public virtual DbSet<LoanCharge> LoanCharges { get; set; }

    public virtual DbSet<LoanCollateral> LoanCollaterals { get; set; }

    public virtual DbSet<LoanContract> LoanContracts { get; set; }

    public virtual DbSet<LoanContractAttachment> LoanContractAttachments { get; set; }

    public virtual DbSet<LoanContractDocument> LoanContractDocuments { get; set; }

    public virtual DbSet<LoanProduct> LoanProducts { get; set; }

    public virtual DbSet<LoanRepaymentSchedule> LoanRepaymentSchedules { get; set; }

    public virtual DbSet<LoanSettlement> LoanSettlements { get; set; }

    public virtual DbSet<LoanStatusHistory> LoanStatusHistories { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<PolicySetting> PolicySettings { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<Store> Stores { get; set; }

    public virtual DbSet<StoreDayLock> StoreDayLocks { get; set; }

    public virtual DbSet<UserCustomRole> UserCustomRoles { get; set; }

    public virtual DbSet<UserLoginHistory> UserLoginHistories { get; set; }

    public virtual DbSet<UserPermission> UserPermissions { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    public virtual DbSet<UserStoreAssignment> UserStoreAssignments { get; set; }

    public virtual DbSet<VDailyCollection> VDailyCollections { get; set; }

    public virtual DbSet<VOverdueSchedule> VOverdueSchedules { get; set; }

    public virtual DbSet<VStoreOutstandingLoan> VStoreOutstandingLoans { get; set; }

    public virtual DbSet<VUserPermission> VUserPermissions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("app_users_pkey");

            entity.ToTable("app_users");

            entity.HasIndex(e => e.Username, "app_users_username_key").IsUnique();

            entity.Property(e => e.UserId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Email).HasColumnName("email");
            entity.Property(e => e.FailedLoginAttempts).HasColumnName("failed_login_attempts");
            entity.Property(e => e.FullName).HasColumnName("full_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.LastLoginAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("last_login_at");
            entity.Property(e => e.LockedUntil)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("locked_until");
            entity.Property(e => e.MustChangePassword).HasColumnName("must_change_password");
            entity.Property(e => e.PasswordChangedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("password_changed_at");
            entity.Property(e => e.PasswordHash).HasColumnName("password_hash");
            entity.Property(e => e.Phone).HasColumnName("phone");
            entity.Property(e => e.RoleCode).HasColumnName("role_code");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.Username).HasColumnName("username");

            entity.HasOne(d => d.Store).WithMany(p => p.AppUsers)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("app_users_store_id_fkey");
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.AuditLogId).HasName("audit_logs_pkey");

            entity.ToTable("audit_logs");

            entity.HasIndex(e => e.ChangedAt, "ix_audit_logs_changed_at");

            entity.HasIndex(e => e.CustomerId, "ix_audit_logs_customer_id");

            entity.HasIndex(e => e.LoanContractId, "ix_audit_logs_loan_contract_id");

            entity.HasIndex(e => e.StoreId, "ix_audit_logs_store_id");

            entity.HasIndex(e => new { e.TableName, e.RecordId }, "ix_audit_logs_table_name_record_id");

            entity.Property(e => e.AuditLogId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("audit_log_id");
            entity.Property(e => e.ActionCode).HasColumnName("action_code");
            entity.Property(e => e.ChangedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("changed_at");
            entity.Property(e => e.ChangedBy).HasColumnName("changed_by");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.NewData)
                .HasColumnType("jsonb")
                .HasColumnName("new_data");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.OldData)
                .HasColumnType("jsonb")
                .HasColumnName("old_data");
            entity.Property(e => e.RecordId).HasColumnName("record_id");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.TableName).HasColumnName("table_name");

            entity.HasOne(d => d.ChangedByNavigation).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.ChangedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("audit_logs_changed_by_fkey");

            entity.HasOne(d => d.Customer).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("audit_logs_customer_id_fkey");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("audit_logs_loan_contract_id_fkey");

            entity.HasOne(d => d.Store).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("audit_logs_store_id_fkey");
        });

        modelBuilder.Entity<BadDebtCase>(entity =>
        {
            entity.HasKey(e => e.BadDebtCaseId).HasName("bad_debt_cases_pkey");

            entity.ToTable("bad_debt_cases");

            entity.HasIndex(e => e.LoanContractId, "bad_debt_cases_loan_contract_id_key").IsUnique();

            entity.HasIndex(e => e.StatusCode, "ix_bad_debt_cases_status_code");

            entity.HasIndex(e => e.StoreId, "ix_bad_debt_cases_store_id");

            entity.HasIndex(e => e.TransferredAt, "ix_bad_debt_cases_transferred_at");

            entity.Property(e => e.BadDebtCaseId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("bad_debt_case_id");
            entity.Property(e => e.ClosedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("closed_at");
            entity.Property(e => e.ClosedBy).HasColumnName("closed_by");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.OtherOutstandingAmount)
                .HasPrecision(18, 2)
                .HasColumnName("other_outstanding_amount");
            entity.Property(e => e.OutstandingInterestAmount)
                .HasPrecision(18, 2)
                .HasColumnName("outstanding_interest_amount");
            entity.Property(e => e.OutstandingLatePenaltyAmount)
                .HasPrecision(18, 2)
                .HasColumnName("outstanding_late_penalty_amount");
            entity.Property(e => e.OutstandingPeriodicFeeAmount)
                .HasPrecision(18, 2)
                .HasColumnName("outstanding_periodic_fee_amount");
            entity.Property(e => e.OutstandingPrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("outstanding_principal_amount");
            entity.Property(e => e.RecoveredAmountTotal)
                .HasPrecision(18, 2)
                .HasColumnName("recovered_amount_total");
            entity.Property(e => e.StatusCode)
                .HasDefaultValueSql("'OPEN'::text")
                .HasColumnName("status_code");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.TotalOutstandingAmount)
                .HasPrecision(18, 2)
                .HasColumnName("total_outstanding_amount");
            entity.Property(e => e.TransferredAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("transferred_at");
            entity.Property(e => e.TransferredBy).HasColumnName("transferred_by");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.ClosedByNavigation).WithMany(p => p.BadDebtCaseClosedByNavigations)
                .HasForeignKey(d => d.ClosedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("bad_debt_cases_closed_by_fkey");

            entity.HasOne(d => d.LoanContract).WithOne(p => p.BadDebtCase)
                .HasForeignKey<BadDebtCase>(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("bad_debt_cases_loan_contract_id_fkey");

            entity.HasOne(d => d.Store).WithMany(p => p.BadDebtCases)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("bad_debt_cases_store_id_fkey");

            entity.HasOne(d => d.TransferredByNavigation).WithMany(p => p.BadDebtCaseTransferredByNavigations)
                .HasForeignKey(d => d.TransferredBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("bad_debt_cases_transferred_by_fkey");
        });

        modelBuilder.Entity<CashVoucher>(entity =>
        {
            entity.HasKey(e => e.VoucherId).HasName("cash_vouchers_pkey");

            entity.ToTable("cash_vouchers");

            entity.HasIndex(e => e.VoucherNo, "cash_vouchers_voucher_no_key").IsUnique();

            entity.HasIndex(e => e.BusinessDate, "ix_cash_vouchers_business_date");

            entity.HasIndex(e => e.CustomerId, "ix_cash_vouchers_customer_id");

            entity.HasIndex(e => e.LoanContractId, "ix_cash_vouchers_loan_contract_id");

            entity.HasIndex(e => e.ReasonCode, "ix_cash_vouchers_reason_code");

            entity.HasIndex(e => e.StoreId, "ix_cash_vouchers_store_id");

            entity.HasIndex(e => e.VoucherType, "ix_cash_vouchers_voucher_type");

            entity.Property(e => e.VoucherId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("voucher_id");
            entity.Property(e => e.Amount)
                .HasPrecision(18, 2)
                .HasColumnName("amount");
            entity.Property(e => e.ApprovedBy).HasColumnName("approved_by");
            entity.Property(e => e.BusinessDate)
                .HasDefaultValueSql("CURRENT_DATE")
                .HasColumnName("business_date");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DocumentNo).HasColumnName("document_no");
            entity.Property(e => e.IsAdjustment).HasColumnName("is_adjustment");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.PayerReceiverAddress).HasColumnName("payer_receiver_address");
            entity.Property(e => e.PayerReceiverName).HasColumnName("payer_receiver_name");
            entity.Property(e => e.PrintedCount).HasColumnName("printed_count");
            entity.Property(e => e.ReasonCode).HasColumnName("reason_code");
            entity.Property(e => e.RelatedVoucherId).HasColumnName("related_voucher_id");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.VoucherDatetime)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("voucher_datetime");
            entity.Property(e => e.VoucherNo).HasColumnName("voucher_no");
            entity.Property(e => e.VoucherType).HasColumnName("voucher_type");
            entity.Property(e => e.PaymentMethod)
                .HasColumnName("payment_method");
            entity.Property(e => e.BankName).HasColumnName("bank_name");
            entity.Property(e => e.BankAccountNumber).HasColumnName("bank_account_number");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.CashVoucherApprovedByNavigations)
                .HasForeignKey(d => d.ApprovedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_vouchers_approved_by_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CashVoucherCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_vouchers_created_by_fkey");

            entity.HasOne(d => d.Customer).WithMany(p => p.CashVouchers)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_vouchers_customer_id_fkey");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.CashVouchers)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_vouchers_loan_contract_id_fkey");

            entity.HasOne(d => d.RelatedVoucher).WithMany(p => p.InverseRelatedVoucher)
                .HasForeignKey(d => d.RelatedVoucherId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_vouchers_related_voucher_id_fkey");

            entity.HasOne(d => d.Store).WithMany(p => p.CashVouchers)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_vouchers_store_id_fkey");
        });

        modelBuilder.Entity<CashVoucherAllocation>(entity =>
        {
            entity.HasKey(e => e.AllocationId).HasName("cash_voucher_allocations_pkey");

            entity.ToTable("cash_voucher_allocations");

            entity.HasIndex(e => e.ChargeId, "ix_cash_voucher_allocations_charge_id");

            entity.HasIndex(e => e.ComponentCode, "ix_cash_voucher_allocations_component_code");

            entity.HasIndex(e => e.LoanContractId, "ix_cash_voucher_allocations_loan_contract_id");

            entity.HasIndex(e => e.ScheduleId, "ix_cash_voucher_allocations_schedule_id");

            entity.HasIndex(e => e.SettlementId, "ix_cash_voucher_allocations_settlement_id");

            entity.HasIndex(e => e.VoucherId, "ix_cash_voucher_allocations_voucher_id");

            entity.Property(e => e.AllocationId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("allocation_id");
            entity.Property(e => e.Amount)
                .HasPrecision(18, 2)
                .HasColumnName("amount");
            entity.Property(e => e.ChargeId).HasColumnName("charge_id");
            entity.Property(e => e.ComponentCode).HasColumnName("component_code");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.ScheduleId).HasColumnName("schedule_id");
            entity.Property(e => e.SettlementId).HasColumnName("settlement_id");
            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");

            entity.HasOne(d => d.Charge).WithMany(p => p.CashVoucherAllocations)
                .HasForeignKey(d => d.ChargeId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_voucher_allocations_charge_id_fkey");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.CashVoucherAllocations)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_voucher_allocations_loan_contract_id_fkey");

            entity.HasOne(d => d.Schedule).WithMany(p => p.CashVoucherAllocations)
                .HasForeignKey(d => d.ScheduleId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_voucher_allocations_schedule_id_fkey");

            entity.HasOne(d => d.Settlement).WithMany(p => p.CashVoucherAllocations)
                .HasForeignKey(d => d.SettlementId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_voucher_allocations_settlement_id_fkey");

            entity.HasOne(d => d.Voucher).WithMany(p => p.CashVoucherAllocations)
                .HasForeignKey(d => d.VoucherId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("cash_voucher_allocations_voucher_id_fkey");
        });

        modelBuilder.Entity<Collaborator>(entity =>
        {
            entity.HasKey(e => e.CollaboratorId).HasName("collaborators_pkey");

            entity.ToTable("collaborators");

            entity.HasIndex(e => e.IsActive, "idx_collaborators_is_active");

            entity.HasIndex(e => e.StoreId, "idx_collaborators_store_id");

            entity.Property(e => e.CollaboratorId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("collaborator_id");
            entity.Property(e => e.CommissionRate)
                .HasPrecision(5, 2)
                .HasComment("Tỷ lệ hoa hồng (%) áp dụng cho CTV, ví dụ 2.50 = 2.5%. NULL = chưa cấu hình.")
                .HasColumnName("commission_rate");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.FullName).HasColumnName("full_name");
            entity.Property(e => e.IdNumber).HasColumnName("id_number");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Phone).HasColumnName("phone");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Collaborators)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("collaborators_created_by_fkey");

            entity.HasOne(d => d.Store).WithMany(p => p.Collaborators)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("collaborators_store_id_fkey");
        });

        modelBuilder.Entity<CustomRole>(entity =>
        {
            entity.HasKey(e => e.CustomRoleId).HasName("custom_roles_pkey");

            entity.ToTable("custom_roles");

            entity.HasIndex(e => e.IsActive, "ix_custom_roles_is_active");

            entity.HasIndex(e => e.StoreId, "ix_custom_roles_store_id");

            entity.HasIndex(e => new { e.RoleName, e.StoreId }, "uq_custom_roles_role_name_store").IsUnique();

            entity.Property(e => e.CustomRoleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("custom_role_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.RoleName).HasColumnName("role_name");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CustomRoleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("custom_roles_created_by_fkey");

            entity.HasOne(d => d.Store).WithMany(p => p.CustomRoles)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("custom_roles_store_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.CustomRoleUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("custom_roles_updated_by_fkey");
        });

        modelBuilder.Entity<CustomRolePermission>(entity =>
        {
            entity.HasKey(e => e.CustomRolePermissionId).HasName("custom_role_permissions_pkey");

            entity.ToTable("custom_role_permissions");

            entity.HasIndex(e => e.CustomRoleId, "ix_custom_role_permissions_custom_role_id");

            entity.HasIndex(e => e.PermissionId, "ix_custom_role_permissions_permission_id");

            entity.HasIndex(e => new { e.CustomRoleId, e.PermissionId }, "uq_custom_role_permissions").IsUnique();

            entity.Property(e => e.CustomRolePermissionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("custom_role_permission_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CustomRoleId).HasColumnName("custom_role_id");
            entity.Property(e => e.PermissionId).HasColumnName("permission_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CustomRolePermissions)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("custom_role_permissions_created_by_fkey");

            entity.HasOne(d => d.CustomRole).WithMany(p => p.CustomRolePermissions)
                .HasForeignKey(d => d.CustomRoleId)
                .HasConstraintName("custom_role_permissions_custom_role_id_fkey");

            entity.HasOne(d => d.Permission).WithMany(p => p.CustomRolePermissions)
                .HasForeignKey(d => d.PermissionId)
                .HasConstraintName("custom_role_permissions_permission_id_fkey");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("customers_pkey");

            entity.ToTable("customers");

            entity.HasIndex(e => e.ReferredByCollaboratorId, "idx_customers_referred_by_collaborator_id").HasFilter("(referred_by_collaborator_id IS NOT NULL)");

            entity.HasIndex(e => e.AssignedToUserId, "ix_customers_assigned_to_user_id");

            entity.HasIndex(e => e.CustomerCode, "uq_customers_customer_code")
                .IsUnique()
                .HasFilter("(customer_code IS NOT NULL)");

            entity.HasIndex(e => e.NationalIdHash, "uq_customers_national_id_hash")
                .IsUnique()
                .HasFilter("(national_id_hash IS NOT NULL)");

            entity.Property(e => e.CustomerId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("customer_id");
            entity.Property(e => e.Address).HasColumnName("address");
            entity.Property(e => e.AssignedToUserId).HasColumnName("assigned_to_user_id");
            entity.Property(e => e.BadHistoryNote).HasColumnName("bad_history_note");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CustomerCode).HasColumnName("customer_code");
            entity.Property(e => e.DateOfBirth).HasColumnName("date_of_birth");
            entity.Property(e => e.FirstSourceType).HasColumnName("first_source_type");
            entity.Property(e => e.FirstStoreId).HasColumnName("first_store_id");
            entity.Property(e => e.FullName).HasColumnName("full_name");
            entity.Property(e => e.Gender).HasColumnName("gender");
            entity.Property(e => e.HasBadHistory).HasColumnName("has_bad_history");
            entity.Property(e => e.NationalId).HasColumnName("national_id");
            entity.Property(e => e.NationalIdHash)
                .HasMaxLength(64)
                .HasColumnName("national_id_hash");
            entity.Property(e => e.Phone).HasColumnName("phone");
            entity.Property(e => e.ReferredByCollaboratorId).HasColumnName("referred_by_collaborator_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.AssignedToUser).WithMany(p => p.CustomerAssignedToUsers)
                .HasForeignKey(d => d.AssignedToUserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("customers_assigned_to_user_id_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CustomerCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("customers_created_by_fkey");

            entity.HasOne(d => d.FirstStore).WithMany(p => p.Customers)
                .HasForeignKey(d => d.FirstStoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("customers_first_store_id_fkey");

            entity.HasOne(d => d.ReferredByCollaborator).WithMany(p => p.Customers)
                .HasForeignKey(d => d.ReferredByCollaboratorId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("customers_referred_by_collaborator_id_fkey");
        });

        modelBuilder.Entity<CustomerDocument>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("customer_documents_pkey");

            entity.ToTable("customer_documents");

            entity.HasIndex(e => e.CustomerId, "ix_customer_documents_customer_id");

            entity.Property(e => e.DocumentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("document_id");
            entity.Property(e => e.ContentType).HasColumnName("content_type");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.DocumentType)
                .HasDefaultValueSql("'OTHER'::text")
                .HasColumnName("document_type");
            entity.Property(e => e.FileName).HasColumnName("file_name");
            entity.Property(e => e.FileSize).HasColumnName("file_size");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.StoragePath).HasColumnName("storage_path");
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("uploaded_at");
            entity.Property(e => e.UploadedBy).HasColumnName("uploaded_by");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerDocuments)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("customer_documents_customer_id_fkey");

            entity.HasOne(d => d.UploadedByNavigation).WithMany(p => p.CustomerDocuments)
                .HasForeignKey(d => d.UploadedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("customer_documents_uploaded_by_fkey");
        });

        modelBuilder.Entity<CustomerSource>(entity =>
        {
            entity.HasKey(e => e.SourceId).HasName("customer_sources_pkey");

            entity.ToTable("customer_sources", tb => tb.HasComment("Danh mục luồng khách hàng (nguồn khách dẫn đến hợp đồng vay)."));

            entity.HasIndex(e => e.SourceName, "uq_customer_source_name").IsUnique();

            entity.Property(e => e.SourceId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("source_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasComment("true = đang dùng; false = đã ẩn (không cho chọn nhưng giữ lịch sử).")
                .HasColumnName("is_active");
            entity.Property(e => e.SortOrder)
                .HasComment("Thứ tự hiển thị trong danh sách chọn.")
                .HasColumnName("sort_order");
            entity.Property(e => e.SourceName)
                .HasMaxLength(100)
                .HasComment("Tên luồng khách, VD: CTV, Facebook, Tiktok...")
                .HasColumnName("source_name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CustomerSources)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("customer_sources_created_by_fkey");
        });

        modelBuilder.Entity<CustomerVisit>(entity =>
        {
            entity.HasKey(e => e.VisitId).HasName("customer_visits_pkey");

            entity.ToTable("customer_visits");

            entity.Property(e => e.VisitId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("visit_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.HandledBy).HasColumnName("handled_by");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.SourceType).HasColumnName("source_type");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.VisitDate)
                .HasDefaultValueSql("CURRENT_DATE")
                .HasColumnName("visit_date");
            entity.Property(e => e.VisitType).HasColumnName("visit_type");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerVisits)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("customer_visits_customer_id_fkey");

            entity.HasOne(d => d.HandledByNavigation).WithMany(p => p.CustomerVisits)
                .HasForeignKey(d => d.HandledBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("customer_visits_handled_by_fkey");

            entity.HasOne(d => d.Store).WithMany(p => p.CustomerVisits)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("customer_visits_store_id_fkey");
        });

        modelBuilder.Entity<DataAccessLog>(entity =>
        {
            entity.HasKey(e => e.AccessLogId).HasName("data_access_logs_pkey");

            entity.ToTable("data_access_logs");

            entity.HasIndex(e => e.AccessedAt, "ix_data_access_logs_accessed_at").IsDescending();

            entity.HasIndex(e => e.ResourceType, "ix_data_access_logs_resource_type");

            entity.HasIndex(e => new { e.ResourceType, e.ResourceId }, "ix_data_access_logs_resource_type_id");

            entity.HasIndex(e => e.StoreId, "ix_data_access_logs_store_id");

            entity.HasIndex(e => e.UserId, "ix_data_access_logs_user_id");

            entity.Property(e => e.AccessLogId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("access_log_id");
            entity.Property(e => e.AccessedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("accessed_at");
            entity.Property(e => e.Action).HasColumnName("action");
            entity.Property(e => e.IpAddress).HasColumnName("ip_address");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.QueryParams)
                .HasColumnType("jsonb")
                .HasColumnName("query_params");
            entity.Property(e => e.ResourceId).HasColumnName("resource_id");
            entity.Property(e => e.ResourceType).HasColumnName("resource_type");
            entity.Property(e => e.ResponseStatus).HasColumnName("response_status");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Store).WithMany(p => p.DataAccessLogs)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("data_access_logs_store_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.DataAccessLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("data_access_logs_user_id_fkey");
        });

        modelBuilder.Entity<InsuranceContract>(entity =>
        {
            entity.HasKey(e => e.InsuranceContractId).HasName("insurance_contracts_pkey");

            entity.ToTable("insurance_contracts");

            entity.HasIndex(e => e.LoanContractId, "insurance_contracts_loan_contract_id_key").IsUnique();

            entity.Property(e => e.InsuranceContractId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("insurance_contract_id");
            entity.Property(e => e.CoverageAmount)
                .HasPrecision(18, 2)
                .HasColumnName("coverage_amount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.EffectiveFrom).HasColumnName("effective_from");
            entity.Property(e => e.EffectiveTo).HasColumnName("effective_to");
            entity.Property(e => e.InsuranceName).HasColumnName("insurance_name");
            entity.Property(e => e.IsMandatory)
                .HasDefaultValue(true)
                .HasColumnName("is_mandatory");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.PolicyNumber).HasColumnName("policy_number");
            entity.Property(e => e.PremiumAmount)
                .HasPrecision(18, 2)
                .HasColumnName("premium_amount");
            entity.Property(e => e.ProviderName).HasColumnName("provider_name");
            entity.Property(e => e.StatusCode)
                .HasDefaultValueSql("'ACTIVE'::text")
                .HasColumnName("status_code");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.LoanContract).WithOne(p => p.InsuranceContract)
                .HasForeignKey<InsuranceContract>(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("insurance_contracts_loan_contract_id_fkey");
        });

        modelBuilder.Entity<LoanCharge>(entity =>
        {
            entity.HasKey(e => e.ChargeId).HasName("loan_charges_pkey");

            entity.ToTable("loan_charges");

            entity.HasIndex(e => e.ChargeCode, "ix_loan_charges_charge_code");

            entity.HasIndex(e => new { e.DueDate, e.StatusCode }, "ix_loan_charges_due_date_status");

            entity.HasIndex(e => e.LoanContractId, "ix_loan_charges_loan_contract_id");

            entity.HasIndex(e => e.ScheduleId, "ix_loan_charges_schedule_id");

            entity.HasIndex(e => e.StatusCode, "ix_loan_charges_status_code");

            entity.Property(e => e.ChargeId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("charge_id");
            entity.Property(e => e.Amount)
                .HasPrecision(18, 2)
                .HasColumnName("amount");
            entity.Property(e => e.ChargeCode).HasColumnName("charge_code");
            entity.Property(e => e.ChargeDate)
                .HasDefaultValueSql("CURRENT_DATE")
                .HasColumnName("charge_date");
            entity.Property(e => e.ChargeName).HasColumnName("charge_name");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DueDate)
                .HasDefaultValueSql("CURRENT_DATE")
                .HasColumnName("due_date");
            entity.Property(e => e.IsSystemGenerated).HasColumnName("is_system_generated");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.PaidAmount)
                .HasPrecision(18, 2)
                .HasColumnName("paid_amount");
            entity.Property(e => e.ScheduleId).HasColumnName("schedule_id");
            entity.Property(e => e.StatusCode)
                .HasDefaultValueSql("'OPEN'::text")
                .HasColumnName("status_code");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.WaivedAmount)
                .HasPrecision(18, 2)
                .HasColumnName("waived_amount");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.LoanCharges)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_charges_created_by_fkey");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.LoanCharges)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_charges_loan_contract_id_fkey");

            entity.HasOne(d => d.Schedule).WithMany(p => p.LoanCharges)
                .HasForeignKey(d => d.ScheduleId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_charges_schedule_id_fkey");
        });

        modelBuilder.Entity<LoanCollateral>(entity =>
        {
            entity.HasKey(e => e.CollateralId).HasName("loan_collaterals_pkey");

            entity.ToTable("loan_collaterals");

            entity.HasIndex(e => e.LoanContractId, "ix_loan_collaterals_loan_contract_id");

            entity.Property(e => e.CollateralId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("collateral_id");
            entity.Property(e => e.CollateralType).HasColumnName("collateral_type");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Detail).HasColumnName("detail");
            entity.Property(e => e.EstimatedValue)
                .HasPrecision(18, 2)
                .HasColumnName("estimated_value");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.SerialNumber).HasColumnName("serial_number");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.LoanCollaterals)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_collaterals_created_by_fkey");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.LoanCollaterals)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_collaterals_loan_contract_id_fkey");
        });

        modelBuilder.Entity<LoanContract>(entity =>
        {
            entity.HasKey(e => e.LoanContractId).HasName("loan_contracts_pkey");

            entity.ToTable("loan_contracts");

            entity.HasIndex(e => e.CustomerSourceId, "idx_loan_contracts_customer_source_id");

            entity.HasIndex(e => e.AssignedToUserId, "ix_loan_contracts_assigned_to_user_id");

            entity.HasIndex(e => e.CustomerId, "ix_loan_contracts_customer_id");

            entity.HasIndex(e => e.DisbursementDate, "ix_loan_contracts_disbursement_date");

            entity.HasIndex(e => e.StatusCode, "ix_loan_contracts_status_code");

            entity.HasIndex(e => e.StoreId, "ix_loan_contracts_store_id");

            entity.HasIndex(e => e.ContractNo, "loan_contracts_contract_no_key").IsUnique();

            entity.Property(e => e.LoanContractId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("loan_contract_id");
            entity.Property(e => e.ApplicationDate)
                .HasDefaultValueSql("CURRENT_DATE")
                .HasColumnName("application_date");
            entity.Property(e => e.ApprovedBy).HasColumnName("approved_by");
            entity.Property(e => e.ApprovedDate).HasColumnName("approved_date");
            entity.Property(e => e.AssignedToUserId).HasColumnName("assigned_to_user_id");
            entity.Property(e => e.BadDebtStartDaySnapshot)
                .HasDefaultValue((short)11)
                .HasColumnName("bad_debt_start_day_snapshot");
            entity.Property(e => e.CancellationReason).HasColumnName("cancellation_reason");
            entity.Property(e => e.CancelledAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("cancelled_at");
            entity.Property(e => e.CancelledBy).HasColumnName("cancelled_by");
            entity.Property(e => e.ContractNo).HasColumnName("contract_no");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.ContractType)
                .HasDefaultValueSql("'INSTALLMENT'")
                .HasColumnName("contract_type");
            entity.Property(e => e.CustomerSourceId)
                .HasComment("Luồng khách dẫn đến hợp đồng này (FK → customer_sources).")
                .HasColumnName("customer_source_id");
            entity.Property(e => e.DisbursedBy).HasColumnName("disbursed_by");
            entity.Property(e => e.DisbursementDate).HasColumnName("disbursement_date");
            entity.Property(e => e.EarlySettlementPenaltyRateSnapshot)
                .HasPrecision(5, 2)
                .HasDefaultValue(5.00m)
                .HasColumnName("early_settlement_penalty_rate_snapshot");
            entity.Property(e => e.FileFeeAmountSnapshot)
                .HasPrecision(18, 2)
                .HasColumnName("file_fee_amount_snapshot");
            entity.Property(e => e.FirstDueDate).HasColumnName("first_due_date");
            entity.Property(e => e.FixedMonthlyFeeAmountSnapshot)
                .HasPrecision(18, 2)
                .HasColumnName("fixed_monthly_fee_amount_snapshot");
            entity.Property(e => e.InsuranceAmountSnapshot)
                .HasPrecision(18, 2)
                .HasColumnName("insurance_amount_snapshot");
            entity.Property(e => e.PawnInterestAmountPerMillionPerDaySnapshot)
                .HasPrecision(18, 2)
                .HasColumnName("pawn_interest_amount_per_million_per_day_snapshot");
            entity.Property(e => e.PawnFeeAmountPerMillionPerDaySnapshot)
                .HasPrecision(18, 2)
                .HasColumnName("pawn_fee_amount_per_million_per_day_snapshot");
            entity.Property(e => e.PawnPeriodDaysSnapshot)
                .HasDefaultValue((short)10)
                .HasColumnName("pawn_period_days_snapshot");
            entity.Property(e => e.InsuranceDiscountRateSnapshot)
                .HasPrecision(5, 2)
                .HasComment("% chiết khấu bảo hiểm tại thời điểm tạo hợp đồng (snapshot từ chính sách áp dụng). Chỉ Admin xem.")
                .HasColumnName("insurance_discount_rate_snapshot");
            entity.Property(e => e.InterestRateMonthlySnapshot)
                .HasPrecision(9, 6)
                .HasColumnName("interest_rate_monthly_snapshot");
            entity.Property(e => e.LatePaymentPenaltyRateSnapshot)
                .HasPrecision(5, 2)
                .HasDefaultValue(8.00m)
                .HasColumnName("late_payment_penalty_rate_snapshot");
            entity.Property(e => e.LatePaymentStartDaySnapshot)
                .HasDefaultValue((short)4)
                .HasColumnName("late_payment_start_day_snapshot");
            entity.Property(e => e.LoanProductId).HasColumnName("loan_product_id");
            entity.Property(e => e.MaturityDate).HasColumnName("maturity_date");
            entity.Property(e => e.NetDisbursedAmount)
                .HasPrecision(18, 2)
                .HasColumnName("net_disbursed_amount");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.PreviousLoanContractId).HasColumnName("previous_loan_contract_id");
            entity.Property(e => e.PrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("principal_amount");
            entity.Property(e => e.QlkvRateMonthlySnapshot)
                .HasPrecision(9, 6)
                .HasColumnName("qlkv_rate_monthly_snapshot");
            entity.Property(e => e.QltsRateMonthlySnapshot)
                .HasPrecision(9, 6)
                .HasColumnName("qlts_rate_monthly_snapshot");
            entity.Property(e => e.SettledAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("settled_at");
            entity.Property(e => e.StatusCode)
                .HasDefaultValueSql("'DRAFT'::text")
                .HasColumnName("status_code");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.TermMonths).HasColumnName("term_months");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.WarningDaysSnapshot)
                .HasDefaultValueSql("ARRAY[5, 10, 15]")
                .HasColumnName("warning_days_snapshot");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.LoanContractApprovedByNavigations)
                .HasForeignKey(d => d.ApprovedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contracts_approved_by_fkey");

            entity.HasOne(d => d.AssignedToUser).WithMany(p => p.LoanContractAssignedToUsers)
                .HasForeignKey(d => d.AssignedToUserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("loan_contracts_assigned_to_user_id_fkey");

            entity.HasOne(d => d.CancelledByNavigation).WithMany(p => p.LoanContractCancelledByNavigations)
                .HasForeignKey(d => d.CancelledBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contracts_cancelled_by_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.LoanContractCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contracts_created_by_fkey");

            entity.HasOne(d => d.Customer).WithMany(p => p.LoanContracts)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contracts_customer_id_fkey");

            entity.HasOne(d => d.CustomerSource).WithMany(p => p.LoanContracts)
                .HasForeignKey(d => d.CustomerSourceId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("loan_contracts_customer_source_id_fkey");

            entity.HasOne(d => d.DisbursedByNavigation).WithMany(p => p.LoanContractDisbursedByNavigations)
                .HasForeignKey(d => d.DisbursedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contracts_disbursed_by_fkey");

            entity.HasOne(d => d.LoanProduct).WithMany(p => p.LoanContracts)
                .HasForeignKey(d => d.LoanProductId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contracts_loan_product_id_fkey");

            entity.HasOne(d => d.PreviousLoanContract).WithMany(p => p.InversePreviousLoanContract)
                .HasForeignKey(d => d.PreviousLoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contracts_previous_loan_contract_id_fkey");

            entity.HasOne(d => d.Store).WithMany(p => p.LoanContracts)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contracts_store_id_fkey");
        });

        modelBuilder.Entity<LoanContractAttachment>(entity =>
        {
            entity.HasKey(e => e.AttachmentId).HasName("loan_contract_attachments_pkey");

            entity.ToTable("loan_contract_attachments");

            entity.HasIndex(e => e.LoanContractId, "ix_loan_contract_attachments_loan_contract_id");

            entity.HasIndex(e => e.LoanContractId, "loan_contract_attachments_loan_contract_id_key").IsUnique();

            entity.Property(e => e.AttachmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("attachment_id");
            entity.Property(e => e.ContentType)
                .HasDefaultValueSql("'application/pdf'::text")
                .HasColumnName("content_type");
            entity.Property(e => e.FileName).HasColumnName("file_name");
            entity.Property(e => e.FileSize).HasColumnName("file_size");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.StoragePath).HasColumnName("storage_path");
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("uploaded_at");
            entity.Property(e => e.UploadedBy).HasColumnName("uploaded_by");

            entity.HasOne(d => d.LoanContract).WithOne(p => p.LoanContractAttachment)
                .HasForeignKey<LoanContractAttachment>(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contract_attachments_loan_contract_id_fkey");

            entity.HasOne(d => d.UploadedByNavigation).WithMany(p => p.LoanContractAttachments)
                .HasForeignKey(d => d.UploadedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contract_attachments_uploaded_by_fkey");
        });

        modelBuilder.Entity<LoanContractDocument>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("loan_contract_documents_pkey");

            entity.ToTable("loan_contract_documents");

            entity.HasIndex(e => e.LoanContractId, "ix_loan_contract_documents_loan_contract_id");

            entity.Property(e => e.DocumentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("document_id");
            entity.Property(e => e.ContentType).HasColumnName("content_type");
            entity.Property(e => e.DocumentType)
                .HasDefaultValueSql("'OTHER'::text")
                .HasColumnName("document_type");
            entity.Property(e => e.FileName).HasColumnName("file_name");
            entity.Property(e => e.FileSize).HasColumnName("file_size");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.StoragePath).HasColumnName("storage_path");
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("uploaded_at");
            entity.Property(e => e.UploadedBy).HasColumnName("uploaded_by");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.LoanContractDocuments)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contract_documents_loan_contract_id_fkey");

            entity.HasOne(d => d.UploadedByNavigation).WithMany(p => p.LoanContractDocuments)
                .HasForeignKey(d => d.UploadedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_contract_documents_uploaded_by_fkey");
        });

        modelBuilder.Entity<LoanProduct>(entity =>
        {
            entity.HasKey(e => e.LoanProductId).HasName("loan_products_pkey");

            entity.ToTable("loan_products");

            entity.HasIndex(e => new { e.StoreId, e.ProductCode }, "uq_loan_products_code").IsUnique();

            entity.Property(e => e.LoanProductId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("loan_product_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.DefaultFileFeeAmount)
                .HasPrecision(18, 2)
                .HasColumnName("default_file_fee_amount");
            entity.Property(e => e.DefaultInsuranceRate)
                .HasPrecision(9, 6)
                .HasColumnName("default_insurance_rate");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.FixedMonthlyFeeAmount)
                .HasPrecision(18, 2)
                .HasColumnName("fixed_monthly_fee_amount");
            entity.Property(e => e.InterestRateMonthly)
                .HasPrecision(9, 6)
                .HasColumnName("interest_rate_monthly");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.MaxPrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("max_principal_amount");
            entity.Property(e => e.MaxTermMonths)
                .HasDefaultValue(1)
                .HasColumnName("max_term_months");
            entity.Property(e => e.MinPrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("min_principal_amount");
            entity.Property(e => e.MinTermMonths)
                .HasDefaultValue(1)
                .HasColumnName("min_term_months");
            entity.Property(e => e.ProductCode).HasColumnName("product_code");
            entity.Property(e => e.ProductName).HasColumnName("product_name");
            entity.Property(e => e.QlkvRateMonthly)
                .HasPrecision(9, 6)
                .HasColumnName("qlkv_rate_monthly");
            entity.Property(e => e.QltsRateMonthly)
                .HasPrecision(9, 6)
                .HasColumnName("qlts_rate_monthly");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Store).WithMany(p => p.LoanProducts)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_products_store_id_fkey");
        });

        modelBuilder.Entity<LoanRepaymentSchedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId).HasName("loan_repayment_schedules_pkey");

            entity.ToTable("loan_repayment_schedules");

            entity.HasIndex(e => e.DueDate, "ix_loan_repayment_schedules_due_date");

            entity.HasIndex(e => new { e.DueDate, e.StatusCode }, "ix_loan_repayment_schedules_due_date_status");

            entity.HasIndex(e => e.LoanContractId, "ix_loan_repayment_schedules_loan_contract_id");

            entity.HasIndex(e => e.StatusCode, "ix_loan_repayment_schedules_status_code");

            entity.HasIndex(e => new { e.LoanContractId, e.PeriodNo }, "uq_loan_repayment_schedules").IsUnique();

            entity.Property(e => e.ScheduleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("schedule_id");
            entity.Property(e => e.ActualDayCount).HasColumnName("actual_day_count");
            entity.Property(e => e.ClosingPrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("closing_principal_amount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.DueInterestAmount)
                .HasPrecision(18, 2)
                .HasColumnName("due_interest_amount");
            entity.Property(e => e.DueLatePenaltyAmount)
                .HasPrecision(18, 2)
                .HasColumnName("due_late_penalty_amount");
            entity.Property(e => e.DuePeriodicFeeAmount)
                .HasPrecision(18, 2)
                .HasColumnName("due_periodic_fee_amount");
            entity.Property(e => e.DuePrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("due_principal_amount");
            entity.Property(e => e.DueQlkvAmount)
                .HasPrecision(18, 2)
                .HasColumnName("due_qlkv_amount");
            entity.Property(e => e.DueQltsAmount)
                .HasPrecision(18, 2)
                .HasColumnName("due_qlts_amount");
            entity.Property(e => e.FullyPaidAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fully_paid_at");
            entity.Property(e => e.InstallmentAmount)
                .HasPrecision(18, 2)
                .HasColumnName("installment_amount");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.OpeningPrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("opening_principal_amount");
            entity.Property(e => e.PaidInterestAmount)
                .HasPrecision(18, 2)
                .HasColumnName("paid_interest_amount");
            entity.Property(e => e.PaidLatePenaltyAmount)
                .HasPrecision(18, 2)
                .HasColumnName("paid_late_penalty_amount");
            entity.Property(e => e.PaidPeriodicFeeAmount)
                .HasPrecision(18, 2)
                .HasColumnName("paid_periodic_fee_amount");
            entity.Property(e => e.PaidPrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("paid_principal_amount");
            entity.Property(e => e.PaidQlkvAmount)
                .HasPrecision(18, 2)
                .HasColumnName("paid_qlkv_amount");
            entity.Property(e => e.PaidQltsAmount)
                .HasPrecision(18, 2)
                .HasColumnName("paid_qlts_amount");
            entity.Property(e => e.PeriodFromDate).HasColumnName("period_from_date");
            entity.Property(e => e.PeriodNo).HasColumnName("period_no");
            entity.Property(e => e.PeriodToDate).HasColumnName("period_to_date");
            entity.Property(e => e.StatusCode)
                .HasDefaultValueSql("'PENDING'::text")
                .HasColumnName("status_code");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.LoanRepaymentSchedules)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_repayment_schedules_loan_contract_id_fkey");
        });

        modelBuilder.Entity<LoanSettlement>(entity =>
        {
            entity.HasKey(e => e.SettlementId).HasName("loan_settlements_pkey");

            entity.ToTable("loan_settlements");

            entity.HasIndex(e => e.IsFinalized, "ix_loan_settlements_is_finalized");

            entity.HasIndex(e => e.LoanContractId, "ix_loan_settlements_loan_contract_id");

            entity.HasIndex(e => e.SettlementDate, "ix_loan_settlements_settlement_date");

            entity.HasIndex(e => e.SettlementNo, "loan_settlements_settlement_no_key").IsUnique();

            entity.Property(e => e.SettlementId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("settlement_id");
            entity.Property(e => e.AccruedInterestAmount)
                .HasPrecision(18, 2)
                .HasColumnName("accrued_interest_amount");
            entity.Property(e => e.AccruedPeriodicFeeAmount)
                .HasPrecision(18, 2)
                .HasColumnName("accrued_periodic_fee_amount");
            entity.Property(e => e.ActualElapsedDays).HasColumnName("actual_elapsed_days");
            entity.Property(e => e.CompletionRatio)
                .HasPrecision(9, 6)
                .HasColumnName("completion_ratio");
            entity.Property(e => e.ContractTotalDays).HasColumnName("contract_total_days");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DiscountAmount)
                .HasPrecision(18, 2)
                .HasColumnName("discount_amount");
            entity.Property(e => e.EarlySettlementPenaltyAmount)
                .HasPrecision(18, 2)
                .HasColumnName("early_settlement_penalty_amount");
            entity.Property(e => e.FinalizedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("finalized_at");
            entity.Property(e => e.FinalizedBy).HasColumnName("finalized_by");
            entity.Property(e => e.IsFinalized).HasColumnName("is_finalized");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.OtherReceivableAmount)
                .HasPrecision(18, 2)
                .HasColumnName("other_receivable_amount");
            entity.Property(e => e.RemainingPrincipalAmount)
                .HasPrecision(18, 2)
                .HasColumnName("remaining_principal_amount");
            entity.Property(e => e.RequestDate)
                .HasDefaultValueSql("CURRENT_DATE")
                .HasColumnName("request_date");
            entity.Property(e => e.SettlementDate).HasColumnName("settlement_date");
            entity.Property(e => e.SettlementNo).HasColumnName("settlement_no");
            entity.Property(e => e.SettlementType).HasColumnName("settlement_type");
            entity.Property(e => e.TotalSettlementAmount)
                .HasPrecision(18, 2)
                .HasColumnName("total_settlement_amount");
            entity.Property(e => e.UnpaidLatePenaltyAmount)
                .HasPrecision(18, 2)
                .HasColumnName("unpaid_late_penalty_amount");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.LoanSettlementCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_settlements_created_by_fkey");

            entity.HasOne(d => d.FinalizedByNavigation).WithMany(p => p.LoanSettlementFinalizedByNavigations)
                .HasForeignKey(d => d.FinalizedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_settlements_finalized_by_fkey");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.LoanSettlements)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_settlements_loan_contract_id_fkey");
        });

        modelBuilder.Entity<LoanStatusHistory>(entity =>
        {
            entity.HasKey(e => e.LoanStatusHistoryId).HasName("loan_status_histories_pkey");

            entity.ToTable("loan_status_histories");

            entity.HasIndex(e => e.ChangedAt, "ix_loan_status_histories_changed_at");

            entity.HasIndex(e => e.LoanContractId, "ix_loan_status_histories_loan_contract_id");

            entity.Property(e => e.LoanStatusHistoryId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("loan_status_history_id");
            entity.Property(e => e.ChangedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("changed_at");
            entity.Property(e => e.ChangedBy).HasColumnName("changed_by");
            entity.Property(e => e.FromStatusCode).HasColumnName("from_status_code");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Reason).HasColumnName("reason");
            entity.Property(e => e.ToStatusCode).HasColumnName("to_status_code");

            entity.HasOne(d => d.ChangedByNavigation).WithMany(p => p.LoanStatusHistories)
                .HasForeignKey(d => d.ChangedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_status_histories_changed_by_fkey");

            entity.HasOne(d => d.LoanContract).WithMany(p => p.LoanStatusHistories)
                .HasForeignKey(d => d.LoanContractId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("loan_status_histories_loan_contract_id_fkey");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("permissions_pkey");

            entity.ToTable("permissions");

            entity.HasIndex(e => e.IsActive, "ix_permissions_is_active");

            entity.HasIndex(e => e.Resource, "ix_permissions_resource");

            entity.HasIndex(e => e.PermissionCode, "permissions_permission_code_key").IsUnique();

            entity.HasIndex(e => new { e.Resource, e.Action }, "uq_permissions_resource_action").IsUnique();

            entity.Property(e => e.PermissionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("permission_id");
            entity.Property(e => e.Action).HasColumnName("action");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsDelegatable).HasColumnName("is_delegatable");
            entity.Property(e => e.PermissionCode).HasColumnName("permission_code");
            entity.Property(e => e.PermissionName).HasColumnName("permission_name");
            entity.Property(e => e.Resource).HasColumnName("resource");
        });

        modelBuilder.Entity<PolicySetting>(entity =>
        {
            entity.HasKey(e => e.PolicyId).HasName("policy_settings_pkey");

            entity.ToTable("policy_settings");

            entity.Property(e => e.PolicyId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("policy_id");
            entity.Property(e => e.BadDebtStartDay)
                .HasDefaultValue((short)11)
                .HasColumnName("bad_debt_start_day");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.EarlySettlementPenaltyRate)
                .HasPrecision(5, 2)
                .HasDefaultValue(5.00m)
                .HasColumnName("early_settlement_penalty_rate");
            entity.Property(e => e.EffectiveFrom).HasColumnName("effective_from");
            entity.Property(e => e.EffectiveTo).HasColumnName("effective_to");
            entity.Property(e => e.InsuranceDiscountRate)
                .HasPrecision(5, 2)
                .HasComment("% chiết khấu bảo hiểm công ty nhận từ nhà bảo hiểm (0-100). Chỉ Admin xem.")
                .HasColumnName("insurance_discount_rate");
            entity.Property(e => e.LatePaymentPenaltyRate)
                .HasPrecision(5, 2)
                .HasDefaultValue(8.00m)
                .HasColumnName("late_payment_penalty_rate");
            entity.Property(e => e.LatePaymentStartDay)
                .HasDefaultValue((short)4)
                .HasColumnName("late_payment_start_day");
            entity.Property(e => e.WarningDays)
                .HasDefaultValueSql("ARRAY[5, 10, 15]")
                .HasColumnName("warning_days");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.PolicySettings)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("policy_settings_created_by_fkey");

            entity.HasMany(d => d.Stores).WithMany(p => p.Policies)
                .UsingEntity<Dictionary<string, object>>(
                    "PolicySettingStore",
                    r => r.HasOne<Store>().WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("policy_setting_stores_store_id_fkey"),
                    l => l.HasOne<PolicySetting>().WithMany()
                        .HasForeignKey("PolicyId")
                        .HasConstraintName("policy_setting_stores_policy_id_fkey"),
                    j =>
                    {
                        j.HasKey("PolicyId", "StoreId").HasName("policy_setting_stores_pkey");
                        j.ToTable("policy_setting_stores");
                        j.HasIndex(new[] { "StoreId" }, "idx_policy_setting_stores_store_id");
                        j.IndexerProperty<Guid>("PolicyId").HasColumnName("policy_id");
                        j.IndexerProperty<Guid>("StoreId").HasColumnName("store_id");
                    });
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => e.RolePermissionId).HasName("role_permissions_pkey");

            entity.ToTable("role_permissions");

            entity.HasIndex(e => e.PermissionId, "ix_role_permissions_permission_id");

            entity.HasIndex(e => e.RoleCode, "ix_role_permissions_role_code");

            entity.HasIndex(e => new { e.RoleCode, e.PermissionId }, "uq_role_permissions").IsUnique();

            entity.Property(e => e.RolePermissionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("role_permission_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.PermissionId).HasColumnName("permission_id");
            entity.Property(e => e.RoleCode).HasColumnName("role_code");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("role_permissions_created_by_fkey");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.PermissionId)
                .HasConstraintName("role_permissions_permission_id_fkey");
        });

        modelBuilder.Entity<Store>(entity =>
        {
            entity.HasKey(e => e.StoreId).HasName("stores_pkey");

            entity.ToTable("stores");

            entity.HasIndex(e => e.StoreCode, "stores_store_code_key").IsUnique();

            entity.Property(e => e.StoreId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("store_id");
            entity.Property(e => e.Address).HasColumnName("address");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.OpenedOn).HasColumnName("opened_on");
            entity.Property(e => e.Phone).HasColumnName("phone");
            entity.Property(e => e.StoreCode).HasColumnName("store_code");
            entity.Property(e => e.StoreName).HasColumnName("store_name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<StoreDayLock>(entity =>
        {
            entity.HasKey(e => new { e.StoreId, e.BusinessDate }).HasName("store_day_locks_pkey");

            entity.ToTable("store_day_locks");

            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.BusinessDate).HasColumnName("business_date");
            entity.Property(e => e.IsLocked)
                .HasDefaultValue(true)
                .HasColumnName("is_locked");
            entity.Property(e => e.LockedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("locked_at");
            entity.Property(e => e.LockedBy).HasColumnName("locked_by");
            entity.Property(e => e.Note).HasColumnName("note");

            entity.HasOne(d => d.LockedByNavigation).WithMany(p => p.StoreDayLocks)
                .HasForeignKey(d => d.LockedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("store_day_locks_locked_by_fkey");

            entity.HasOne(d => d.Store).WithMany(p => p.StoreDayLocks)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("store_day_locks_store_id_fkey");
        });

        modelBuilder.Entity<UserCustomRole>(entity =>
        {
            entity.HasKey(e => e.UserCustomRoleId).HasName("user_custom_roles_pkey");

            entity.ToTable("user_custom_roles");

            entity.HasIndex(e => e.CustomRoleId, "ix_user_custom_roles_custom_role_id");

            entity.HasIndex(e => e.UserId, "ix_user_custom_roles_user_id");

            entity.HasIndex(e => new { e.UserId, e.CustomRoleId }, "uq_user_custom_roles").IsUnique();

            entity.Property(e => e.UserCustomRoleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_custom_role_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CustomRoleId).HasColumnName("custom_role_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.UserCustomRoleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_custom_roles_created_by_fkey");

            entity.HasOne(d => d.CustomRole).WithMany(p => p.UserCustomRoles)
                .HasForeignKey(d => d.CustomRoleId)
                .HasConstraintName("user_custom_roles_custom_role_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserCustomRoleUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_custom_roles_user_id_fkey");
        });

        modelBuilder.Entity<UserLoginHistory>(entity =>
        {
            entity.HasKey(e => e.LoginHistoryId).HasName("user_login_history_pkey");

            entity.ToTable("user_login_history");

            entity.HasIndex(e => e.IpAddress, "ix_user_login_history_ip_address");

            entity.HasIndex(e => e.LoginAt, "ix_user_login_history_login_at").IsDescending();

            entity.HasIndex(e => e.UserId, "ix_user_login_history_user_id");

            entity.HasIndex(e => new { e.Username, e.IsSuccess }, "ix_user_login_history_username_is_success");

            entity.Property(e => e.LoginHistoryId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("login_history_id");
            entity.Property(e => e.FailureReason).HasColumnName("failure_reason");
            entity.Property(e => e.IpAddress).HasColumnName("ip_address");
            entity.Property(e => e.IsSuccess).HasColumnName("is_success");
            entity.Property(e => e.LoginAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("login_at");
            entity.Property(e => e.UserAgent).HasColumnName("user_agent");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Username).HasColumnName("username");

            entity.HasOne(d => d.User).WithMany(p => p.UserLoginHistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_login_history_user_id_fkey");
        });

        modelBuilder.Entity<UserPermission>(entity =>
        {
            entity.HasKey(e => e.UserPermissionId).HasName("user_permissions_pkey");

            entity.ToTable("user_permissions");

            entity.HasIndex(e => e.PermissionId, "ix_user_permissions_permission_id");

            entity.HasIndex(e => e.UserId, "ix_user_permissions_user_id");

            entity.HasIndex(e => new { e.UserId, e.PermissionId }, "uq_user_permissions").IsUnique();

            entity.Property(e => e.UserPermissionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_permission_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.IsGranted)
                .HasDefaultValue(true)
                .HasColumnName("is_granted");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.PermissionId).HasColumnName("permission_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.UserPermissionCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_permissions_created_by_fkey");

            entity.HasOne(d => d.Permission).WithMany(p => p.UserPermissions)
                .HasForeignKey(d => d.PermissionId)
                .HasConstraintName("user_permissions_permission_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserPermissionUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_permissions_user_id_fkey");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("user_sessions_pkey");

            entity.ToTable("user_sessions");

            entity.HasIndex(e => e.ExpiresAt, "ix_user_sessions_expires_at").HasFilter("(revoked_at IS NULL)");

            entity.HasIndex(e => e.RefreshTokenHash, "ix_user_sessions_refresh_token_hash").HasFilter("(revoked_at IS NULL)");

            entity.HasIndex(e => e.UserId, "ix_user_sessions_user_id");

            entity.Property(e => e.SessionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("session_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.DeviceInfo).HasColumnName("device_info");
            entity.Property(e => e.ExpiresAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("expires_at");
            entity.Property(e => e.IpAddress).HasColumnName("ip_address");
            entity.Property(e => e.RefreshTokenHash).HasColumnName("refresh_token_hash");
            entity.Property(e => e.RevokedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("revoked_at");
            entity.Property(e => e.RevokedReason).HasColumnName("revoked_reason");
            entity.Property(e => e.UserAgent).HasColumnName("user_agent");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_sessions_user_id_fkey");
        });

        modelBuilder.Entity<UserStoreAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("pk_user_store_assignments");

            entity.ToTable("user_store_assignments", tb => tb.HasComment("Ánh xạ nhiều-nhiều giữa Quản lý vùng (REGIONAL_MANAGER) và các chi nhánh phụ trách."));

            entity.HasIndex(e => e.StoreId, "ix_user_store_assignments_store_id");

            entity.HasIndex(e => e.UserId, "ix_user_store_assignments_user_id");

            entity.HasIndex(e => new { e.UserId, e.StoreId }, "uq_user_store_assignments").IsUnique();

            entity.Property(e => e.AssignmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("assignment_id");
            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("now()")
                .HasComment("Thời điểm gán chi nhánh cho quản lý vùng.")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("assigned_at");
            entity.Property(e => e.StoreId)
                .HasComment("FK → stores. Chi nhánh nằm trong vùng quản lý.")
                .HasColumnName("store_id");
            entity.Property(e => e.UserId)
                .HasComment("FK → app_users. Phải là REGIONAL_MANAGER.")
                .HasColumnName("user_id");

            entity.HasOne(d => d.Store).WithMany(p => p.UserStoreAssignments)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_usa_store");

            entity.HasOne(d => d.User).WithMany(p => p.UserStoreAssignments)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_usa_user");
        });

        modelBuilder.Entity<VDailyCollection>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("v_daily_collections");

            entity.Property(e => e.BusinessDate).HasColumnName("business_date");
            entity.Property(e => e.FeeCollected).HasColumnName("fee_collected");
            entity.Property(e => e.InterestCollected).HasColumnName("interest_collected");
            entity.Property(e => e.NetCashflow).HasColumnName("net_cashflow");
            entity.Property(e => e.PenaltyCollected).HasColumnName("penalty_collected");
            entity.Property(e => e.PrincipalCollected).HasColumnName("principal_collected");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.StoreName).HasColumnName("store_name");
            entity.Property(e => e.TotalPayments).HasColumnName("total_payments");
            entity.Property(e => e.TotalReceipts).HasColumnName("total_receipts");
            entity.Property(e => e.VoucherCount).HasColumnName("voucher_count");
        });

        modelBuilder.Entity<VOverdueSchedule>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("v_overdue_schedules");

            entity.Property(e => e.BadDebtStartDaySnapshot).HasColumnName("bad_debt_start_day_snapshot");
            entity.Property(e => e.ContractNo).HasColumnName("contract_no");
            entity.Property(e => e.CustomerCode).HasColumnName("customer_code");
            entity.Property(e => e.CustomerName).HasColumnName("customer_name");
            entity.Property(e => e.CustomerPhone).HasColumnName("customer_phone");
            entity.Property(e => e.DaysOverdue).HasColumnName("days_overdue");
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.LoanContractId).HasColumnName("loan_contract_id");
            entity.Property(e => e.PeriodNo).HasColumnName("period_no");
            entity.Property(e => e.RiskLevel).HasColumnName("risk_level");
            entity.Property(e => e.ScheduleId).HasColumnName("schedule_id");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.StoreName).HasColumnName("store_name");
            entity.Property(e => e.TotalUnpaid).HasColumnName("total_unpaid");
            entity.Property(e => e.UnpaidFee).HasColumnName("unpaid_fee");
            entity.Property(e => e.UnpaidInterest).HasColumnName("unpaid_interest");
            entity.Property(e => e.UnpaidPenalty).HasColumnName("unpaid_penalty");
            entity.Property(e => e.UnpaidPrincipal).HasColumnName("unpaid_principal");
            entity.Property(e => e.UnpaidQlkv).HasColumnName("unpaid_qlkv");
            entity.Property(e => e.UnpaidQlts).HasColumnName("unpaid_qlts");
        });

        modelBuilder.Entity<VStoreOutstandingLoan>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("v_store_outstanding_loans");

            entity.Property(e => e.ActiveLoanCount).HasColumnName("active_loan_count");
            entity.Property(e => e.BadDebtCount).HasColumnName("bad_debt_count");
            entity.Property(e => e.OutstandingPrincipalAmount).HasColumnName("outstanding_principal_amount");
            entity.Property(e => e.StoreCode).HasColumnName("store_code");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.StoreName).HasColumnName("store_name");
            entity.Property(e => e.TotalPrincipalAmount).HasColumnName("total_principal_amount");
        });

        modelBuilder.Entity<VUserPermission>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("v_user_permissions");

            entity.Property(e => e.Action).HasColumnName("action");
            entity.Property(e => e.FullName).HasColumnName("full_name");
            entity.Property(e => e.HasPermission).HasColumnName("has_permission");
            entity.Property(e => e.PermissionCode).HasColumnName("permission_code");
            entity.Property(e => e.PermissionId).HasColumnName("permission_id");
            entity.Property(e => e.PermissionName).HasColumnName("permission_name");
            entity.Property(e => e.PermissionSource).HasColumnName("permission_source");
            entity.Property(e => e.Resource).HasColumnName("resource");
            entity.Property(e => e.RoleCode).HasColumnName("role_code");
            entity.Property(e => e.StoreId).HasColumnName("store_id");
            entity.Property(e => e.StoreName).HasColumnName("store_name");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Username).HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
