// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class Customer
{
    public Guid CustomerId { get; set; }

    public string NationalId { get; set; } = null!;

    public string FullName { get; set; } = null!;

    public DateOnly? DateOfBirth { get; set; }

    public string? Gender { get; set; }

    public string? Phone { get; set; }

    public string? Address { get; set; }

    public string? FirstSourceType { get; set; }

    public bool HasBadHistory { get; set; }

    public string? BadHistoryNote { get; set; }

    public Guid? FirstStoreId { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string? NationalIdHash { get; set; }

    public string? CustomerCode { get; set; }

    public Guid? ReferredByCollaboratorId { get; set; }

    public Guid? AssignedToUserId { get; set; }

    public virtual AppUser? AssignedToUser { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<CashVoucher> CashVouchers { get; set; } = new List<CashVoucher>();

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual ICollection<CustomerDocument> CustomerDocuments { get; set; } = new List<CustomerDocument>();

    public virtual ICollection<CustomerVisit> CustomerVisits { get; set; } = new List<CustomerVisit>();

    public virtual Store? FirstStore { get; set; }

    public virtual ICollection<LoanContract> LoanContracts { get; set; } = new List<LoanContract>();

    public virtual Collaborator? ReferredByCollaborator { get; set; }
}