// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class CustomRole
{
    public Guid CustomRoleId { get; set; }

    public string RoleName { get; set; } = null!;

    public string? Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    public Guid? StoreId { get; set; }

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual ICollection<CustomRolePermission> CustomRolePermissions { get; set; } = new List<CustomRolePermission>();

    public virtual Store? Store { get; set; }

    public virtual AppUser? UpdatedByNavigation { get; set; }

    public virtual ICollection<UserCustomRole> UserCustomRoles { get; set; } = new List<UserCustomRole>();
}