// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class CustomerDocument
{
    public Guid DocumentId { get; set; }

    public Guid CustomerId { get; set; }

    public string DocumentType { get; set; } = null!;

    public string FileName { get; set; } = null!;

    public long FileSize { get; set; }

    public string ContentType { get; set; } = null!;

    public string StoragePath { get; set; } = null!;

    public string? Note { get; set; }

    public Guid? UploadedBy { get; set; }

    public DateTime UploadedAt { get; set; }

    public virtual Customer Customer { get; set; } = null!;

    public virtual AppUser? UploadedByNavigation { get; set; }
}