// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

/// <summary>
/// Danh mục luồng khách hàng (nguồn khách dẫn đến hợp đồng vay).
/// </summary>
public partial class CustomerSource
{
    public Guid SourceId { get; set; }

    /// <summary>
    /// Tên luồng khách, VD: CTV, Facebook, Tiktok...
    /// </summary>
    public string SourceName { get; set; } = null!;

    /// <summary>
    /// true = đang dùng; false = đã ẩn (không cho chọn nhưng giữ lịch sử).
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Thứ tự hiển thị trong danh sách chọn.
    /// </summary>
    public int SortOrder { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual ICollection<LoanContract> LoanContracts { get; set; } = new List<LoanContract>();
}