// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class CustomerVisit
{
    public Guid VisitId { get; set; }

    public Guid StoreId { get; set; }

    public Guid CustomerId { get; set; }

    public DateOnly VisitDate { get; set; }

    public string VisitType { get; set; } = null!;

    public string? SourceType { get; set; }

    public Guid? HandledBy { get; set; }

    public string? Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Customer Customer { get; set; } = null!;

    public virtual AppUser? HandledByNavigation { get; set; }

    public virtual Store Store { get; set; } = null!;
}