// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net;

namespace CrediFlow.DataContext.Models;

public partial class DataAccessLog
{
    public Guid AccessLogId { get; set; }

    public Guid UserId { get; set; }

    public Guid? StoreId { get; set; }

    public string ResourceType { get; set; } = null!;

    public Guid? ResourceId { get; set; }

    public string Action { get; set; } = null!;

    public DateTime AccessedAt { get; set; }

    public IPAddress? IpAddress { get; set; }

    public string? QueryParams { get; set; }

    public int? ResponseStatus { get; set; }

    public string? Note { get; set; }

    public virtual Store? Store { get; set; }

    public virtual AppUser User { get; set; } = null!;
}