// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class InsuranceContract
{
    public Guid InsuranceContractId { get; set; }

    public Guid LoanContractId { get; set; }

    public string ProviderName { get; set; } = null!;

    public string? PolicyNumber { get; set; }

    public string? InsuranceName { get; set; }

    public bool IsMandatory { get; set; }

    public decimal PremiumAmount { get; set; }

    public decimal? CoverageAmount { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    public string StatusCode { get; set; } = null!;

    public string? Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual LoanContract LoanContract { get; set; } = null!;
}