// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class LoanProduct
{
    public Guid LoanProductId { get; set; }

    public Guid? StoreId { get; set; }

    public string ProductCode { get; set; } = null!;

    public string ProductName { get; set; } = null!;

    public string? Description { get; set; }

    public decimal MinPrincipalAmount { get; set; }

    public decimal MaxPrincipalAmount { get; set; }

    public int MinTermMonths { get; set; }

    public int MaxTermMonths { get; set; }

    public decimal InterestRateMonthly { get; set; }

    public decimal DefaultFileFeeAmount { get; set; }

    public decimal DefaultInsuranceRate { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public decimal QlkvRateMonthly { get; set; }

    public decimal QltsRateMonthly { get; set; }

    public decimal FixedMonthlyFeeAmount { get; set; }

    public virtual ICollection<LoanContract> LoanContracts { get; set; } = new List<LoanContract>();

    public virtual Store? Store { get; set; }
}