// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class LoanStatusHistory
{
    public Guid LoanStatusHistoryId { get; set; }

    public Guid LoanContractId { get; set; }

    public string? FromStatusCode { get; set; }

    public string ToStatusCode { get; set; } = null!;

    public DateTime ChangedAt { get; set; }

    public Guid? ChangedBy { get; set; }

    public string? Reason { get; set; }

    public string? Note { get; set; }

    public virtual AppUser? ChangedByNavigation { get; set; }

    public virtual LoanContract LoanContract { get; set; } = null!;
}