// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class LoanSettlement
{
    public Guid SettlementId { get; set; }

    public string SettlementNo { get; set; } = null!;

    public Guid LoanContractId { get; set; }

    public string SettlementType { get; set; } = null!;

    public DateOnly RequestDate { get; set; }

    public DateOnly? SettlementDate { get; set; }

    public int ActualElapsedDays { get; set; }

    public int ContractTotalDays { get; set; }

    public decimal CompletionRatio { get; set; }

    public decimal RemainingPrincipalAmount { get; set; }

    public decimal AccruedInterestAmount { get; set; }

    public decimal AccruedPeriodicFeeAmount { get; set; }

    public decimal UnpaidLatePenaltyAmount { get; set; }

    public decimal EarlySettlementPenaltyAmount { get; set; }

    public decimal OtherReceivableAmount { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal TotalSettlementAmount { get; set; }

    public bool IsFinalized { get; set; }

    public DateTime? FinalizedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? FinalizedBy { get; set; }

    public string? Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CashVoucherAllocation> CashVoucherAllocations { get; set; } = new List<CashVoucherAllocation>();

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual AppUser? FinalizedByNavigation { get; set; }

    public virtual LoanContract LoanContract { get; set; } = null!;
}