// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class LoanContract
{
    public Guid LoanContractId { get; set; }

    public string ContractNo { get; set; } = null!;

    public Guid StoreId { get; set; }

    public Guid CustomerId { get; set; }

    public string ContractType { get; set; } = null!;

    public Guid? LoanProductId { get; set; }

    public Guid? PreviousLoanContractId { get; set; }

    public string StatusCode { get; set; } = null!;

    public DateOnly ApplicationDate { get; set; }

    public DateOnly? ApprovedDate { get; set; }

    public DateOnly? DisbursementDate { get; set; }

    public DateOnly? FirstDueDate { get; set; }

    public DateOnly? MaturityDate { get; set; }

    public int TermMonths { get; set; }

    public decimal PrincipalAmount { get; set; }

    public decimal NetDisbursedAmount { get; set; }

    public decimal InterestRateMonthlySnapshot { get; set; }

    public decimal FileFeeAmountSnapshot { get; set; }

    public decimal InsuranceAmountSnapshot { get; set; }

    public decimal PawnInterestAmountPerMillionPerDaySnapshot { get; set; }

    public decimal PawnFeeAmountPerMillionPerDaySnapshot { get; set; }

    public short PawnPeriodDaysSnapshot { get; set; }

    public decimal EarlySettlementPenaltyRateSnapshot { get; set; }

    public decimal LatePaymentPenaltyRateSnapshot { get; set; }

    public short LatePaymentStartDaySnapshot { get; set; }

    public short BadDebtStartDaySnapshot { get; set; }

    public List<short> WarningDaysSnapshot { get; set; } = null!;

    public DateTime? CancelledAt { get; set; }

    public Guid? CancelledBy { get; set; }

    public string? CancellationReason { get; set; }

    public DateTime? SettledAt { get; set; }

    public string? Note { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? ApprovedBy { get; set; }

    public Guid? DisbursedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public decimal QlkvRateMonthlySnapshot { get; set; }

    public decimal QltsRateMonthlySnapshot { get; set; }

    public decimal FixedMonthlyFeeAmountSnapshot { get; set; }

    public Guid? AssignedToUserId { get; set; }

    /// <summary>
    /// % chiết khấu bảo hiểm tại thời điểm tạo hợp đồng (snapshot từ chính sách áp dụng). Chỉ Admin xem.
    /// </summary>
    public decimal InsuranceDiscountRateSnapshot { get; set; }

    /// <summary>
    /// Luồng khách dẫn đến hợp đồng này (FK → customer_sources).
    /// </summary>
    public Guid? CustomerSourceId { get; set; }

    public virtual AppUser? ApprovedByNavigation { get; set; }

    public virtual AppUser? AssignedToUser { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual BadDebtCase? BadDebtCase { get; set; }

    public virtual AppUser? CancelledByNavigation { get; set; }

    public virtual ICollection<CashVoucherAllocation> CashVoucherAllocations { get; set; } = new List<CashVoucherAllocation>();

    public virtual ICollection<CashVoucher> CashVouchers { get; set; } = new List<CashVoucher>();

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual Customer Customer { get; set; } = null!;

    public virtual CustomerSource? CustomerSource { get; set; }

    public virtual AppUser? DisbursedByNavigation { get; set; }

    public virtual InsuranceContract? InsuranceContract { get; set; }

    public virtual ICollection<LoanContract> InversePreviousLoanContract { get; set; } = new List<LoanContract>();

    public virtual ICollection<LoanCharge> LoanCharges { get; set; } = new List<LoanCharge>();

    public virtual ICollection<LoanCollateral> LoanCollaterals { get; set; } = new List<LoanCollateral>();

    public virtual LoanContractAttachment? LoanContractAttachment { get; set; }

    public virtual ICollection<LoanContractDocument> LoanContractDocuments { get; set; } = new List<LoanContractDocument>();

    public virtual LoanProduct? LoanProduct { get; set; }

    public virtual ICollection<LoanRepaymentSchedule> LoanRepaymentSchedules { get; set; } = new List<LoanRepaymentSchedule>();

    public virtual ICollection<LoanSettlement> LoanSettlements { get; set; } = new List<LoanSettlement>();

    public virtual ICollection<LoanStatusHistory> LoanStatusHistories { get; set; } = new List<LoanStatusHistory>();

    public virtual LoanContract? PreviousLoanContract { get; set; }

    public virtual Store Store { get; set; } = null!;
}
