// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class LoanCollateral
{
    public Guid CollateralId { get; set; }

    public Guid LoanContractId { get; set; }

    public string CollateralType { get; set; } = null!;

    public string Description { get; set; } = null!;

    public string? SerialNumber { get; set; }

    public decimal? EstimatedValue { get; set; }

    public string? Detail { get; set; }

    public string? Note { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual LoanContract LoanContract { get; set; } = null!;
}