// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class LoanCharge
{
    public Guid ChargeId { get; set; }

    public Guid LoanContractId { get; set; }

    public Guid? ScheduleId { get; set; }

    public string ChargeCode { get; set; } = null!;

    public string ChargeName { get; set; } = null!;

    public DateOnly ChargeDate { get; set; }

    public DateOnly DueDate { get; set; }

    public decimal Amount { get; set; }

    public decimal PaidAmount { get; set; }

    public decimal WaivedAmount { get; set; }

    public string StatusCode { get; set; } = null!;

    public bool IsSystemGenerated { get; set; }

    public string? Note { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CashVoucherAllocation> CashVoucherAllocations { get; set; } = new List<CashVoucherAllocation>();

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual LoanContract LoanContract { get; set; } = null!;

    public virtual LoanRepaymentSchedule? Schedule { get; set; }
}