// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class LoanRepaymentSchedule
{
    public Guid ScheduleId { get; set; }

    public Guid LoanContractId { get; set; }

    public int PeriodNo { get; set; }

    public DateOnly PeriodFromDate { get; set; }

    public DateOnly PeriodToDate { get; set; }

    public DateOnly DueDate { get; set; }

    public int ActualDayCount { get; set; }

    public decimal OpeningPrincipalAmount { get; set; }

    public decimal InstallmentAmount { get; set; }

    public decimal DuePrincipalAmount { get; set; }

    public decimal DueInterestAmount { get; set; }

    public decimal DuePeriodicFeeAmount { get; set; }

    public decimal DueLatePenaltyAmount { get; set; }

    public decimal PaidPrincipalAmount { get; set; }

    public decimal PaidInterestAmount { get; set; }

    public decimal PaidPeriodicFeeAmount { get; set; }

    public decimal PaidLatePenaltyAmount { get; set; }

    public decimal ClosingPrincipalAmount { get; set; }

    public string StatusCode { get; set; } = null!;

    public DateTime? FullyPaidAt { get; set; }

    public string? Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public decimal DueQlkvAmount { get; set; }

    public decimal DueQltsAmount { get; set; }

    public decimal PaidQlkvAmount { get; set; }

    public decimal PaidQltsAmount { get; set; }

    public virtual ICollection<CashVoucherAllocation> CashVoucherAllocations { get; set; } = new List<CashVoucherAllocation>();

    public virtual ICollection<LoanCharge> LoanCharges { get; set; } = new List<LoanCharge>();

    public virtual LoanContract LoanContract { get; set; } = null!;
}