// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class PolicySetting
{
    public Guid PolicyId { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    public decimal EarlySettlementPenaltyRate { get; set; }

    public decimal LatePaymentPenaltyRate { get; set; }

    public short LatePaymentStartDay { get; set; }

    public short BadDebtStartDay { get; set; }

    public List<short> WarningDays { get; set; } = null!;

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// % chiết khấu bảo hiểm công ty nhận từ nhà bảo hiểm (0-100). Chỉ Admin xem.
    /// </summary>
    public decimal InsuranceDiscountRate { get; set; }

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual ICollection<Store> Stores { get; set; } = new List<Store>();
}