// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class RolePermission
{
    public Guid RolePermissionId { get; set; }

    public string RoleCode { get; set; } = null!;

    public Guid PermissionId { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual Permission Permission { get; set; } = null!;
}