// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class Store
{
    public Guid StoreId { get; set; }

    public string StoreCode { get; set; } = null!;

    public string StoreName { get; set; } = null!;

    public string? Address { get; set; }

    public string? Phone { get; set; }

    public DateOnly? OpenedOn { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AppUser> AppUsers { get; set; } = new List<AppUser>();

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<BadDebtCase> BadDebtCases { get; set; } = new List<BadDebtCase>();

    public virtual ICollection<CashVoucher> CashVouchers { get; set; } = new List<CashVoucher>();

    public virtual ICollection<Collaborator> Collaborators { get; set; } = new List<Collaborator>();

    public virtual ICollection<CustomRole> CustomRoles { get; set; } = new List<CustomRole>();

    public virtual ICollection<CustomerVisit> CustomerVisits { get; set; } = new List<CustomerVisit>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<DataAccessLog> DataAccessLogs { get; set; } = new List<DataAccessLog>();

    public virtual ICollection<LoanContract> LoanContracts { get; set; } = new List<LoanContract>();

    public virtual ICollection<LoanProduct> LoanProducts { get; set; } = new List<LoanProduct>();

    public virtual ICollection<StoreDayLock> StoreDayLocks { get; set; } = new List<StoreDayLock>();

    public virtual ICollection<UserStoreAssignment> UserStoreAssignments { get; set; } = new List<UserStoreAssignment>();

    public virtual ICollection<PolicySetting> Policies { get; set; } = new List<PolicySetting>();
}