// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class StoreDayLock
{
    public Guid StoreId { get; set; }

    public DateOnly BusinessDate { get; set; }

    public bool IsLocked { get; set; }

    public DateTime LockedAt { get; set; }

    public Guid? LockedBy { get; set; }

    public string? Note { get; set; }

    public virtual AppUser? LockedByNavigation { get; set; }

    public virtual Store Store { get; set; } = null!;
}