// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class UserCustomRole
{
    public Guid UserCustomRoleId { get; set; }

    public Guid UserId { get; set; }

    public Guid CustomRoleId { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual CustomRole CustomRole { get; set; } = null!;

    public virtual AppUser User { get; set; } = null!;
}