// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net;

namespace CrediFlow.DataContext.Models;

public partial class UserLoginHistory
{
    public Guid LoginHistoryId { get; set; }

    public Guid? UserId { get; set; }

    public string Username { get; set; } = null!;

    public DateTime LoginAt { get; set; }

    public IPAddress? IpAddress { get; set; }

    public string? UserAgent { get; set; }

    public bool IsSuccess { get; set; }

    public string? FailureReason { get; set; }

    public virtual AppUser? User { get; set; }
}