// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

/// <summary>
/// Ánh xạ nhiều-nhiều giữa Quản lý vùng (REGIONAL_MANAGER) và các chi nhánh phụ trách.
/// </summary>
public partial class UserStoreAssignment
{
    public Guid AssignmentId { get; set; }

    /// <summary>
    /// FK → app_users. Phải là REGIONAL_MANAGER.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// FK → stores. Chi nhánh nằm trong vùng quản lý.
    /// </summary>
    public Guid StoreId { get; set; }

    /// <summary>
    /// Thời điểm gán chi nhánh cho quản lý vùng.
    /// </summary>
    public DateTime AssignedAt { get; set; }

    public virtual Store Store { get; set; } = null!;

    public virtual AppUser User { get; set; } = null!;
}