// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class UserPermission
{
    public Guid UserPermissionId { get; set; }

    public Guid UserId { get; set; }

    public Guid PermissionId { get; set; }

    public bool IsGranted { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public string? Note { get; set; }

    public virtual AppUser? CreatedByNavigation { get; set; }

    public virtual Permission Permission { get; set; } = null!;

    public virtual AppUser User { get; set; } = null!;
}