// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class VDailyCollection
{
    public Guid? StoreId { get; set; }

    public string? StoreName { get; set; }

    public DateOnly? BusinessDate { get; set; }

    public long? VoucherCount { get; set; }

    public decimal? TotalReceipts { get; set; }

    public decimal? TotalPayments { get; set; }

    public decimal? NetCashflow { get; set; }

    public decimal? PrincipalCollected { get; set; }

    public decimal? InterestCollected { get; set; }

    public decimal? FeeCollected { get; set; }

    public decimal? PenaltyCollected { get; set; }
}