// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class VOverdueSchedule
{
    public Guid? ScheduleId { get; set; }

    public Guid? LoanContractId { get; set; }

    public string? ContractNo { get; set; }

    public Guid? StoreId { get; set; }

    public string? StoreName { get; set; }

    public string? CustomerCode { get; set; }

    public string? CustomerName { get; set; }

    public string? CustomerPhone { get; set; }

    public int? PeriodNo { get; set; }

    public DateOnly? DueDate { get; set; }

    public int? DaysOverdue { get; set; }

    public decimal? UnpaidPrincipal { get; set; }

    public decimal? UnpaidInterest { get; set; }

    public decimal? UnpaidFee { get; set; }

    public decimal? UnpaidQlkv { get; set; }

    public decimal? UnpaidQlts { get; set; }

    public decimal? UnpaidPenalty { get; set; }

    public decimal? TotalUnpaid { get; set; }

    public short? BadDebtStartDaySnapshot { get; set; }

    public string? RiskLevel { get; set; }
}