// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class VStoreOutstandingLoan
{
    public Guid? StoreId { get; set; }

    public string? StoreCode { get; set; }

    public string? StoreName { get; set; }

    public long? ActiveLoanCount { get; set; }

    public decimal? TotalPrincipalAmount { get; set; }

    public decimal? OutstandingPrincipalAmount { get; set; }

    public long? BadDebtCount { get; set; }
}