// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CrediFlow.DataContext.Models;

public partial class VUserPermission
{
    public Guid? UserId { get; set; }

    public string? Username { get; set; }

    public string? FullName { get; set; }

    public string? RoleCode { get; set; }

    public Guid? StoreId { get; set; }

    public string? StoreName { get; set; }

    public Guid? PermissionId { get; set; }

    public string? PermissionCode { get; set; }

    public string? PermissionName { get; set; }

    public string? Resource { get; set; }

    public string? Action { get; set; }

    public bool? HasPermission { get; set; }

    public string? PermissionSource { get; set; }
}